#ifndef __Config_h__
#define __Config_h__

#define BTSNOOP_ENABLE                    0




#define CUSTOM_DEVICE_NAME                  "BLE test"

// /* adv configer*/
// #define CUSTOM_ADV_FAST_INTERVAL               40
// #define CUSTOM_ADV_SLOW_INTERVAL               60

#define PUBLIC_ADDRESS 0x946100093831
#define GATT_GAP_NAME CUSTOM_DEVICE_NAME

#define GATT_PRI_SERVICE_MAX_COUNT 20
#define GATT_BLE_MTU_SIZE 23
#define GATT_GAP_SERVICE_HANDLE 0x0001
#define GATT_GAP_CHARACTERISTIC_HANDLE 0x0002
#define GATT_GAP_NAME_HANDLE 0x0003
#define GATT_GAP_CHARACTERISTIC_HANDLE_APPRERANCE 0x0004
#define GATT_GAP_APPEARANCE_HANDLE 0x0005
#define GATT_SERVICE_HANLE 0x0006
#define GATT_CHARACTERISTIC_HANDLE_SER_CHA 0x0007
#define GATT_SER_CHA_HANDLE 0x0008
#define GATT_SER_CHA_HANDLE_CLI 0x0009
#define GATT_CHARACTERISTIC_HANDLE_SUP_FEA 0x000A
#define GATT_SER_SUP_FEATURE 0x000B
#define GATT_DEV_INFO_SERVICE_HANDLE 0x000C
#define GATT_CHARACTERISTIC_MANUFACTURER_NAME_STRING_HANDLE 0x000D
#define GATT_MANUFACTURER_NAME_STRING 0x000E
#define GATT_CHARACTERISTIC_PNP_ID 0x000F
#define GATT_PNP_ID_HANDLE 0x0010
#define GATT_BAS_SERVICE_HANDLE
#define GATT_BAS_CHARACTERISTIC_HANDLE
#define GATT_BAS_LEVEL_HANDLE
#define GATT_BAS_CLIENT_CHARA_CONF_HANDLE

#define GATT_SERVER_MAX_COUNT //GATT最大服务数量

#endif // !__Config_h__
